# Generated by Django 5.1.6 on 2025-06-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='There is no discription', max_length=300),
        ),
    ]
