# Generated by Django 5.1.6 on 2025-06-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='discription',
            field=models.TextField(max_length=10000),
        ),
    ]
